# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Create configuration.properties
      run: echo "" > configuration.properties
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@v3.0.2
      with:
        ignore-maven-wrapper: true

    - name: Get Maven version
      run: |
        PROJECT_VERSION=$(mvn org.apache.maven.plugins:maven-help-plugin:3.1.0:evaluate -Dexpression="project.version" -q -DforceStdout)
        echo "PROJECT_VERSION=$PROJECT_VERSION" >> "$GITHUB_ENV"

    - name: Bump Version
      id: bump
      uses: nnichols/maven-version-bump-action@v3
      with:
        github-token: ${{ secrets.github_token }}

    - name: Print Version
      run: |
        echo 'New Version: ${{steps.bump.outputs.version}}'
        echo "Old Version: $PROJECT_VERSION"

    - name: Set New Project Version
      if: ${{ env.PROJECT_VERSION != steps.bump.outputs.version}}
      run: |
        mvn versions:set -DnewVersion='${{ steps.bump.outputs.version }}'
        echo "Set new version to pom.xml"

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v5

    - name: Release
      if: ${{ env.PROJECT_VERSION != steps.bump.outputs.version}}
      uses: softprops/action-gh-release@v1
      with:
        tag_name: "${{ steps.bump.outputs.version }}"
        files: |
          lab1-server/target/lab1-server.jar
          lab1-server/target/lab1-server.war
          lab1-client/target/lab1-client.jar
          lab1-proxy-api/target/lab1-proxy-api.jar
          lab2-server/target/lab2-server.jar
          lab2-server/target/lab2-server.war
          lab2-client/target/lab2-client.jar
          lab2-proxy-api/target/lab2-proxy-api.jar
          lab3-server/target/lab3-server.jar
          lab3-server/target/lab3-server.war
          lab3-client/target/lab3-client.jar
          lab3-proxy-api/target/lab3-proxy-api.jar
          lab4-server/target/lab4-server.jar
          lab4-server/target/lab4-server.war
          lab4-client/target/lab4-client.jar
          lab4-proxy-api/target/lab4-proxy-api.jar
          lab5-server/target/lab5-server.jar
          lab5-server/target/lab5-server.war
          lab5-client/target/lab5-client.jar
          lab5-proxy-api/target/lab5-proxy-api.jar
          lab6-server/target/lab6-server.jar
          lab6-server/target/lab6-server.war
          lab6-client/target/lab6-client.jar
          lab6-proxy-api/target/lab6-proxy-api.jar
          lab7-server/target/lab7-server.jar
          lab7-service-discovery/target/lab7-service-discovery.jar
          lab7-client/target/lab7-client.jar
          lab7-proxy-api/target/lab7-proxy-api.jar
